
exes = bool
include ../make.template

## Dependencias
## -------------------------------------------------------------------
bool: bool.o bool.lexer.o bool.parser.o
bool.lexer.o: bool.lexer.c bool.parser.h
bool.parser.o: bool.parser.c bool.lexer.h
